name: MLCompetitionHub
on: 
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      mail_server: ${{ secrets.mail_server }}
      mail_port: ${{ secrets.mail_port }}
      mail_username: ${{ secrets.mail_username }}
      mail_sender: ${{ secrets.mail_sender }}
      mail_password: ${{ secrets.mail_password }}

    steps:
    - uses: actions/checkout@v1
      
    - name: set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: schedule update new competition
      run: 
        python update_schedule.py
        
    - name: commit
      run: |
        git config --global user.email MLCompetitionHub@github.com
        git config --global user.name MLCompetitionHubGithubAction
        git add .
        git commit -m "schedule update new competition" -a
        
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
